var quirks = [
'albí',
'cec',
'sord',
'calb',
'molt prim',
'molt gras',
'a qui li falta un dit',
'a qui li falta una ma',
'a qui li falta una cama',
'amb cabells molt llargs',
'amb una cicatriu al cap',
'amb una cicatriu a la cara',
'borni',
'amb unes arrecades d’or enormes',
'amb un gran bigoti',
'amb una barba molt llarga',
'que sembla totalment anodí',
'dentadura postissa',
'sense dents',
'a qui li falten les pales',
'amb un diamant per arrecada',
'amb una incrustació a les dents',
'amb una llarga trena',
'zapizot',
'amb un tic',
'que fa mala olor',
'que fa girar un anell constantment',
'que porta un gran bastó',
'que no para de fregar-se les mans',
'que no para de rascar-se',
'molt brut',
'amb marques de verola',
'sense nas',
'gueño',
'que sempre moqueja',
'amb tatuatges a la cara',
'amb un branquilló a la boca de manera permanent',
];
